---
AWSTemplateFormatVersion: "2010-09-09"

Description: "Creates AWS IAM policies for CI/CD user"

Parameters:
  CodeDeployS3Bucket:
    Description: "The name of the S3 bucket for Code Deploy"
    Type: String

Resources:
  GHUploadToS3:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: GH-Upload-To-S3
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:PutObject"
            Resource:
              - Fn::Join:
                - ''
                - - "arn:aws:s3:::"
                  - !Ref CodeDeployS3Bucket
                  - "/*"
              - Fn::Join:
                - ''
                - - "arn:aws:s3:::"
                  - !Ref CodeDeployS3Bucket
      Users:
        - "ghactions-app"

  GHCodeDeploy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: GH-Code-Deploy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "codedeploy:RegisterApplicationRevision"
              - "codedeploy:GetApplicationRevision"
            Resource:
              - Fn::Join:
                - ''
                - - "arn:aws:codedeploy:"
                  - !Ref AWS::Region
                  - ":"
                  - !Ref AWS::AccountId
                  - ":application:csye6225-webapp"
          - Effect: "Allow"
            Action:
              - "codedeploy:CreateDeployment"
              - "codedeploy:GetDeployment"
            Resource:
              - Fn::Join:
                - ''
                - - "arn:aws:codedeploy:"
                  - !Ref AWS::Region
                  - ":"
                  - !Ref AWS::AccountId
                  - ":deploymentgroup:csye6225-webapp/csye6225-webapp-deployment"
          - Effect: "Allow"
            Action:
              - "codedeploy:GetDeploymentConfig"
            Resource:
              - Fn::Join:
                - ''
                - - "arn:aws:codedeploy:"
                  - !Ref AWS::Region
                  - ":"
                  - !Ref AWS::AccountId
                  - ":deploymentconfig:CodeDeployDefault.OneAtATime"
              - Fn::Join:
                - ''
                - - "arn:aws:codedeploy:"
                  - !Ref AWS::Region
                  - ":"
                  - !Ref AWS::AccountId
                  - ":deploymentconfig:CodeDeployDefault.HalfAtATime"
              - Fn::Join:
                - ''
                - - "arn:aws:codedeploy:"
                  - !Ref AWS::Region
                  - ":"
                  - !Ref AWS::AccountId
                  - ":deploymentconfig:CodeDeployDefault.AllAtOnce"
      Users:
        - "ghactions-app"

# "arn:aws:codedeploy:AWS_REGION:AWS_ACCOUNT_ID:application:CODE_DEPLOY_APPLICATION_NAME" 