---
AWSTemplateFormatVersion: "2010-09-09"

Description: "Creates a VPC with 3 subnets in 3 different availability zones in an AWS region."
Parameters:
  VPCCIDRBlock:
    Description: "CIDR block for VPC"
    Type: String
    Default: "10.0.0.0/16"
  VPCName:
    Description: The name of the VPC being created.
    Type: String
    Default: "VPC"